config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get '/about-us' => 'welcome#about', as: :about 
  get '/Contact-Us',     to: 'contacts#new',as: :contact
  get '/Dedicate-A-Song',     to: 'contacts#new', as: :dedicate
  get '/Feedback',     to: 'contacts#new', as: :feedback
  get '/Prayer-Request',     to: 'contacts#new', as: :request
  get '/Testimonials',     to: 'contacts#new', as: :testimonial
  devise_for :admins
  resources :albums do
    resources :audios
  end
  resources :videos
  resources :chapters do
    resources :pages
  end
  resources "contacts", only: [:new, :create]

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :admin
    mount_uploader :video_file, VideoFileUploader
  	validates :title, presence: true, length: { maximum: 250 }	
	validates :video_file, presence: true
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :video_file, :status, :admin_id)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for(@video) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :video_file %>
    <%#= f.input :status %>
    <%= f.hidden_field :admin_id, value: current_admin.id %>
    <br/>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<h1>Listing videos</h1>

<ul class="videos">
  <% @videos.each do |video| %>
    <li>
        <a href="#">
        
        <%= video_tag(video.video_file, autoplay: false, controls: true, size: "200x150")%>
        <br>        
            <b><%= link_to video.title , video %></b>
          <%if admin_signed_in? %>
            <p><%= link_to 'Edit', edit_video_path(video) %> | <%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></p>
           <% end %>
        </a>
    </li>
  <% end %>
</ul>
<%if admin_signed_in? %>
<%= link_to 'New Video', new_video_path %>
<%end%>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<div class="row-fluid">
	<div class="span4">
		<%= video_tag(@video.video_file, autoplay: false, controls: true)%>
		<p>
			<h2>
				 <strong>
				  	<%= @video.title %>
				  </strong>
			</h2>
			
		</p>
	</div>
	<div class="span4">
		
	</div>
	<div class="span4">
		<p class="pull-right">
			<%if admin_signed_in? %>
				<%= link_to 'Edit', edit_video_path(@video) %> |
			<%end%>
			<%= link_to 'Back', videos_path %>
		</p>
	</div>
</div>
   