config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get '/about-us' => 'welcome#about', as: :about 
  get '/Contact-Us',     to: 'contacts#new',as: :contact
  get '/Dedicate-A-Song',     to: 'contacts#new', as: :dedicate
  get '/Feedback',     to: 'contacts#new', as: :feedback
  get '/Prayer-Request',     to: 'contacts#new', as: :request
  get '/Testimonials',     to: 'contacts#new', as: :testimonial
  devise_for :admins
  resources :albums do
    resources :audios
  end
  resources :videos
  resources :chapters do
    resources :pages
  end
  resources "contacts", only: [:new, :create]

end

app/models/album.rb
class Album < ActiveRecord::Base
  	belongs_to :admin
  	has_many :audio, dependent: :destroy
  	mount_uploader :album_cover, AlbumCoverUploader
  	validates :title, presence: true, length: { maximum: 250 }	
	validates :album_cover, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_admin!, only: [:new,:edit, :update, :destroy]

  before_action :set_album, only: [:show, :edit, :update, :destroy]


  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :album_cover, :album_type, :status, :admin_id)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= simple_form_for(@album) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :album_cover %>
    <%#= f.input :album_type %>
    <%#= f.input :status %>
    <%= f.hidden_field :admin_id, value: current_admin.id %>
    <br/>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>
<br/>

<ul class="albums">
  <% @albums.each do |album| %>
    <li>
        <a href="#">
        <%=link_to image_tag(album.album_cover_url(:thumb).to_s,:class=>"img-responsive img-rounded" ), album %> <br>        
            <b><%= link_to album.title , album %></b>
          <%if admin_signed_in? %>
            <p><%= link_to 'Edit', edit_album_path(album) %> | <%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></p>
           <% end %>
        </a>
    </li>
  <% end %>
</ul>

<br>
<%if admin_signed_in? %>
<%= link_to 'New Album', new_album_path %>
<%end%>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<div class="row-fluid">
  <div class="span2">
    <%=image_tag @album.album_cover_url(:thumb).to_s,:class=>"img-responsive img-rounded" %>
  </div>
  <div class="span6">
      <strong>
        <%= @album.title %>
      </strong>  
    
  </div>
  <div class="span4 ">
      <p class="pull-right">
        <%if admin_signed_in? %>
          <%= link_to 'Edit', edit_album_path(@album) %> |
        <%end%>
      <%= link_to 'Back', albums_path %>
      </p>
  </div>
</div>
    <h2>Songs List</h2>
          <%= render @album.audio %>
  <hr/> 
<%if admin_signed_in? %>
 <h2>Add a Song:</h2>
           <%= render "audios/form" %>
<%end%>