config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get '/about-us' => 'welcome#about', as: :about 
  get '/Contact-Us',     to: 'contacts#new',as: :contact
  get '/Dedicate-A-Song',     to: 'contacts#new', as: :dedicate
  get '/Feedback',     to: 'contacts#new', as: :feedback
  get '/Prayer-Request',     to: 'contacts#new', as: :request
  get '/Testimonials',     to: 'contacts#new', as: :testimonial
  devise_for :admins
  resources :albums do
    resources :audios
  end
  resources :videos
  resources :chapters do
    resources :pages
  end
  resources "contacts", only: [:new, :create]

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :admin
  validates :title, presence: true, length: { maximum: 250 }
  has_many :pages, dependent: :destroy	
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
   
   before_action :authenticate_admin!, only: [:new,:edit, :update, :destroy]
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  # GET /chapters
  # GET /chapters.json
  def index
    @chapters = Chapter.all
  end

  # GET /chapters/1
  # GET /chapters/1.json
  def show
  end

  # GET /chapters/new
  def new
    @chapter = Chapter.new
  end

  # GET /chapters/1/edit
  def edit
  end

  # POST /chapters
  # POST /chapters.json
  def create
    @chapter = Chapter.new(chapter_params)

    respond_to do |format|
      if @chapter.save
        format.html { redirect_to @chapter, notice: 'Chapter was successfully created.' }
        format.json { render :show, status: :created, location: @chapter }
      else
        format.html { render :new }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chapters/1
  # PATCH/PUT /chapters/1.json
  def update
    respond_to do |format|
      if @chapter.update(chapter_params)
        format.html { redirect_to @chapter, notice: 'Chapter was successfully updated.' }
        format.json { render :show, status: :ok, location: @chapter }
      else
        format.html { render :edit }
        format.json { render json: @chapter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chapters/1
  # DELETE /chapters/1.json
  def destroy
    @chapter.destroy
    respond_to do |format|
      format.html { redirect_to chapters_url, notice: 'Chapter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chapter
      @chapter = Chapter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chapter_params
      params.require(:chapter).permit(:title, :admin_id)
    end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/views/chapters/_form.html.erb
<%= simple_form_for(@chapter) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
     <%= f.hidden_field :admin_id, value: current_admin.id %>
 <br/>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing chapter</h1>

<%= render 'form' %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', chapters_path %>

app/views/chapters/index.html.erb
<h1>Listing chapters</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chapters.each do |chapter| %>
      <tr>
        <td><%=  %></td>
        
        <td><%= link_to chapter.title, chapter %></td>
         <%if admin_signed_in? %>
        <td><%= link_to 'Edit', edit_chapter_path(chapter) %></td>
        <td><%= link_to 'Destroy', chapter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
 
<%= link_to 'New Chapter', new_chapter_path if admin_signed_in? %>

app/views/chapters/new.html.erb
<h1>New chapter</h1>

<%= render 'form' %>

<%= link_to 'Back', chapters_path %>

app/views/chapters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chapter.title %>
</p>
<h2>Pages</h2>
<%= render @chapter.pages %>
<%if admin_signed_in? %>
<h2>Add a page:</h2>
<%= render "pages/form" %>

<%= link_to 'Edit', edit_chapter_path(@chapter) %> |
<%end%>
<%= link_to 'Back', chapters_path %>