config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'
  get '/about-us' => 'welcome#about', as: :about 
  get '/Contact-Us',     to: 'contacts#new',as: :contact
  get '/Dedicate-A-Song',     to: 'contacts#new', as: :dedicate
  get '/Feedback',     to: 'contacts#new', as: :feedback
  get '/Prayer-Request',     to: 'contacts#new', as: :request
  get '/Testimonials',     to: 'contacts#new', as: :testimonial
  devise_for :admins
  resources :albums do
    resources :audios
  end
  resources :videos
  resources :chapters do
    resources :pages
  end
  resources "contacts", only: [:new, :create]

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable, :lockable, :timeoutable

  has_many :albums
  has_many :audios
  has_many :videos
end

app/models/album.rb
class Album < ActiveRecord::Base
  	belongs_to :admin
  	has_many :audio, dependent: :destroy
  	mount_uploader :album_cover, AlbumCoverUploader
  	validates :title, presence: true, length: { maximum: 250 }	
	validates :album_cover, presence: true
end

app/models/audio.rb
class Audio < ActiveRecord::Base
  belongs_to :album
  belongs_to :admin

  	mount_uploader :audio_file, AudioFileUploader
  	validates :title, presence: true, length: { maximum: 250 }	
	validates :audio_file, presence: true
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :admin
  validates :title, presence: true, length: { maximum: 250 }
  has_many :pages, dependent: :destroy	
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
  #validates :city, presence: true
  #validates :country, presence: true
  validates :message, presence: true  
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :chapter
  belongs_to :admin


  	mount_uploader :page_audio, PageAudioUploader
  	mount_uploader :page_text, PageTextUploader
  	validates :page_audio, presence: true
	validates :page_text, presence: true
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :admin
    mount_uploader :video_file, VideoFileUploader
  	validates :title, presence: true, length: { maximum: 250 }	
	validates :video_file, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_admin!, only: [:new,:edit, :update, :destroy]

  before_action :set_album, only: [:show, :edit, :update, :destroy]


  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :album_cover, :album_type, :status, :admin_id)
    end
end

app/controllers/audios_controller.rb
class AudiosController < ApplicationController

	  before_action :authenticate_admin!



  def create
      @album = Album.find(params[:album_id])
      @audio =@album.audio.create(audio_params)
      redirect_to album_path(@album), notice: 'Audio was successfully created.'      
  end



  def destroy
      @album = Album.find(params[:album_id])
      @audio = @album.audio.find(params[:id])
      @audio.destroy   
      redirect_to album_path(@album) 
  end



  private
    def audio_params
      params.require(:audio).permit(:title, :audio_file,:album_id, :admin_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	  def create
	    @chapter = Chapter.find(params[:chapter_id])
	    @page = @chapter.pages.create(page_params)
	    redirect_to chapter_path(@chapter)
	  end
	   def destroy
	    @chapter = Chapter.find(params[:chapter_id])
	    @page = @chapter.pages.find(params[:id])	    
	    @page.destroy
	     redirect_to chapter_path(@chapter)
	  end
	 
	  private
	    def page_params
	      params.require(:page).permit(:page_audio, :page_text,:chapter_id, :admin_id)
	    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :video_file, :status, :admin_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title)
	    base_title = "Word To World Radio"
	    if page_title.empty?
	      base_title
	    else
	      "#{base_title} | #{page_title}"
	    end
  end
end

app/helpers/audios_helper.rb
module AudiosHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def header 
		   render(partial: 'layouts/header')
	end

	def footer
		 render(partial: 'layouts/footer')
	end
end

app/views/layouts/_devices.html.erb
<!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

app/views/layouts/_footer.html.erb
 <div class="container-fluid">
<p align="center">&copy; 2014 . All Rights Reserved.</p>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid nav-wrap">
  <div class="nav-container">
      <div class="navbar navbar-fluid">
        <div class="navbar-inner">
          <div class="container-fluid main-nav">
            <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>
           
            <%= link_to "Word To World", root_path ,:class=>"brand" %>
            <div class="container-fluid nav-collapse">
              <ul class="nav pull-right">
                <li><%= link_to "Home", root_path  %></li>
                  <%if admin_signed_in? %>
                   
                  <li><%= link_to "Sliders", root_path  %></li>
                    <li><%= link_to "News", root_path %></li>
                    <li><%= link_to "Bible", chapters_path  %></li>
                    <li><%= link_to "Jukebox", albums_path  %></li>              
                    <li><%= link_to "Video Messages", videos_path  %></li>
                    <li class="account_btn"><%= link_to glyph(:off), destroy_admin_session_path, :method => :delete, :class => "account" %>
                        </li>
                  <%else%>
                     <li><%= link_to "About Us", about_path  %></li>
                    <li><%= link_to "Your Daily Bread", root_path %></li>
                    <li><%= link_to "Audio Bible", chapters_path  %></li>
                    <li><%= link_to "Jukebox", albums_path  %></li>              
                    <li><%= link_to "Contact Us", contact_path %></li>
                   <li class="account_btn"><%= link_to glyph(:user), new_admin_session_path, :class => "account" %></li>
                        
                  <%end%>
                 

              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
      </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
 <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title><%= full_title(yield(:title)) %></title></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= render 'layouts/devices' %>
     <%= javascript_include_tag "application" %>
  </head>
  <body>
  	<header>
  	 <%= header %>  
  	</header>
   	<div class="main-fluid">     
         
          <div class="container-modified topbot">
            <%= bootstrap_flash %>
            <%= yield %>    
          </div>
    </div> <!-- /main-container -->
    <footer>
        <%= footer%> 
    </footer>

   

  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for([@chapter, @chapter.pages.build]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :page_audio %>
     <%= f.input :page_text %>
    <%= f.hidden_field :chapter_id, value: @chapter.id%>
    <%= f.hidden_field :admin_id, value: @chapter.admin_id %>
 <br/>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<p>
  <strong>Page Audio:</strong>
  <%= page.page_audio %>
</p>
<p>
  <strong>Page Text:</strong>
  <%= page.page_text %>
</p>
 
<p>
	<%= link_to 'Destroy Page', [page.chapter, page],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>